spring.application.name=Basics
deploy.env=development
#This, is used to define a configuration, which allows spring to automatically(dynamically),get the desired configuration, in the code
#We have set an Environment variable as production, using edit configuration, which will taka precedence over, owr defined env in this file
#Making such environment variables allows us to configuration changes, based on the server/machine, without doing any changes in the code
